apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fastapi
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/philschmi/buml-1
          env:
            - name: TARGET
              value: 'Python Sample v1'
